- Cloudinary.Test/CloudinaryTest.cs
- Cloudinary/Actions/RawUploadParams.cs
- Cloudinary/Api.cs
- Cloudinary/Cloudinary.cs
> Support of UploadLarge

- CHANGELOG.md
- Cloudinary.Test/Cloudinary.Test.csproj
- Cloudinary.Test/CloudinaryTest.cs
- Cloudinary.Test/Configuration/ClodinarySettings.cs
- Cloudinary.Test/IntegrationTestBase.cs
- Cloudinary.Test/SettingsReader.cs
- Cloudinary.Test/app.config.sample
- appveyor.yml
- before_build.ps1
Project was configured for working with appveyor CI service.
> App veyor configuration

- Shared.Tests/CloudinaryTest.cs
- appveyor.yml
The unit tests above failed on non-windows environment.
> Fix TestJsConfig, TestJsConfigFull, TestUploadLocalImageTimeout

- Core/Api.cs
- Shared/Cloudinary.cs
Remove redundant pass by reference
Simplify objects construction
> Fix compilation warnings\notices

- Shared.Tests/CloudinaryTest.cs
- Shared/Actions/RenameParams.cs
> Add `ToType` param to rename API

- Cloudinary.NetCoreTest/IntegrationTestBase.cs
- Cloudinary.Test/AsyncMethodsTest.cs
- Cloudinary.Test/IntegrationTestBase.cs
- Shared.Tests/CloudinaryTest.cs
- Shared.Tests/IntegrationTestBase.cs
> Fix account cleanup after tests

- Shared.Tests/TransformationApiTest.cs
- Shared/Shared.projitems
- Shared/Transforms/BaseExpression.cs
- Shared/Transforms/Condition.cs
- Shared/Transforms/Expression.cs
- Shared/Transforms/ImageTransform.cs
- Shared/Transforms/TextLayer.cs
- Shared/Transforms/Transformation.cs
- Shared/Transforms/VideoTransform.cs
> Add support of user defined variables and expressions

- Shared.Tests/CloudinaryTest.cs
- Shared/Actions/GetResourceParams.cs
- Shared/Actions/GetResourceResult.cs
Added the ability to get pages of multi-pages
> Added pages to GetResourceParams.cs

- Shared.IntegrationTests/AdminApi/ManageUploadPresetsTest.cs
- Shared/Actions/UpdateTransformParams.cs
> Fix `UpdateTransform` Admin API

- Shared.IntegrationTests/UploadApi/ArchiveMethodsTest.cs
- Shared/Actions/BaseParams.cs
> Add support for integer parameter value

- Shared/Actions/ExplicitResult.cs
- Shared/Actions/GetResourceResult.cs
- Shared/Actions/ImageUploadResult.cs
[x] New feature
[ ] Bug fix
[ ] Yes
[x] No
> Add enhanced quality scores to `QualityAnalysis` result

- Shared/Actions/SearchResult.cs
[ ] GitHub issue (Add reference - #XX)
[x] Bug fix
[ ] Yes
[x] No
> Fix `ImageMetadata` list values support in `SearchResult`

- Shared.IntegrationTests/AdminApi/UpdateResourcesTest.cs
- Shared.IntegrationTests/IntegrationTestBase.cs
- Shared.IntegrationTests/SearchApi/SearchApiTest.cs
- Shared/Actions/SearchResult.cs
> Add missing `MetadataFields` in `SearchResult`

- Shared.Tests/Shared.Tests.projitems
- Shared.Tests/Util/StringDictionaryTest.cs
- Shared/StringDictionary.cs
[x] New feature
[ ] Bug fix
[x] Yes
[ ] No
> Add support for list value in metadata

- Shared.Tests/Transformations/Common/ExpressionTest.cs
- Shared.Tests/Transformations/Common/TransformationTest.cs
- Shared/Transforms/BaseExpression.cs
Fix normalize_expression for complex cases
> Fix normalize_expression for complex cases

- Shared.IntegrationTests/Provisioning/AccountApi/AccountProvisioningAsyncTest.cs
- Shared.IntegrationTests/Provisioning/AccountApi/AccountProvisioningTest.cs
- Shared.IntegrationTests/Provisioning/ProvisioningIntegrationTestBase.cs
- Shared/Actions/AssetsManagement/NestedTypes/SafeArrayConverter.cs
- Shared/Actions/AssetsUpload/NestedTypes/AccessControlRule.cs
- Shared/Actions/StreamingProfiles/RepresentationsConverter.cs
- Shared/Provisioning/Actions/UserResult.cs
- Shared/Shared.projitems
> Fix `SubAccountIds` in `UserResult`

- CloudinaryDotNet/FileDescription.cs
> fix on upload very large file bigger then 2Gb

- CloudinaryDotNet.Tests/Parameters/ParametersTest.cs
- CloudinaryDotNet/Actions/AssetsUpload/BasicRawUploadParams.cs
- CloudinaryDotNet/Actions/AssetsUpload/RawUploadParams.cs
> Add support for folder decoupling

- CloudinaryDotNet.IntegrationTests/UploadApi/UploadMethodsTest.cs
- CloudinaryDotNet/Actions/AssetsUpload/AutoUploadParams.cs
- CloudinaryDotNet/Actions/BaseResult.cs
- CloudinaryDotNet/Cloudinary.UploadApi.cs
> Add support for `AutoUploadParams` in `UploadLarge`

- CloudinaryDotNet.Tests/Parameters/MetadataUpdateParamsTest.cs
- CloudinaryDotNet.Tests/Parameters/ParametersTest.cs
- CloudinaryDotNet/Actions/AssetsManagement/UpdateParams.cs
- CloudinaryDotNet/Actions/MetadataFields/MetadataUpdateParams.cs
- CloudinaryDotNet/Constants.cs
> Add support for `ClearInvalid` metadata parameter

- CloudinaryDotNet/CloudinaryDotNet.csproj
> Bump dependencies to fix security vulnerabilities

- CloudinaryDotNet/Actions/AssetsUpload/AutoUploadParams.cs
> Fix `AutoUploadParams` missing properties

- CloudinaryDotNet.Tests/Parameters/ParametersTest.cs
- CloudinaryDotNet/Actions/AssetsUpload/ExplicitParams.cs
> Add support for Dynamic Folder parameters in `Explicit` Upload API

- CloudinaryDotNet.IntegrationTests/UploadApi/ContextMethodsTest.cs
- CloudinaryDotNet/Actions/AssetsUpload/VideoUploadResult.cs
> Fix `Context` in `VideoUploadResult`

- CloudinaryDotNet/Actions/AssetsManagement/GetResourceResult.cs
- CloudinaryDotNet/Actions/AssetsManagement/NestedTypes/LastUpdated.cs
- CloudinaryDotNet/Actions/Search/SearchResource.cs
> Add support for `LastUpdated` field in `GetResourceResult`

- CloudinaryDotNet.IntegrationTests/UploadApi/UploadMethodsTest.cs
- CloudinaryDotNet.Tests/Asset/SignatureTest.cs
- CloudinaryDotNet/Url.cs
> Fix support for unicode public_id url encoding in `BuildUrl`

- CloudinaryDotNet.Tests/AdminApi/UsageReportResponseTest.cs
- CloudinaryDotNet.Tests/CloudinaryDotNet.Tests.csproj
- CloudinaryDotNet/Actions/AssetsManagement/UsageResult.cs
> Add support for `BackgroundRemoval` in `GetUsage` Admin API

- CloudinaryDotNet.IntegrationTests/CloudinaryDotNet.IntegrationTests.csproj
- CloudinaryDotNet.Tests/CloudinaryDotNet.Tests.csproj
- CloudinaryDotNet.Tests/UploadPresetsTest.cs
- CloudinaryDotNet/CloudinaryDotNet.csproj
> Bump vulnerable dependencies

- CloudinaryDotNet.Tests/AdminApi/VisualSearchTest.cs
- CloudinaryDotNet.Tests/CloudinaryDotNet.Tests.csproj
- CloudinaryDotNet.Tests/Constants.cs
- CloudinaryDotNet/Actions/AssetsManagement/VisualSearchParams.cs
- CloudinaryDotNet/Actions/AssetsManagement/VisualSearchResult.cs
- CloudinaryDotNet/Cloudinary.AdminApi.cs
> Add support for `VisualSearch` Admin API

- CloudinaryDotNet.Tests/MockedCloudinary.cs
- CloudinaryDotNet.Tests/SearchTest.cs
- CloudinaryDotNet/ApiShared.Internal.cs
- CloudinaryDotNet/ApiShared.cs
- CloudinaryDotNet/ISignProvider.cs
- CloudinaryDotNet/Search.cs
- CloudinaryDotNet/Url.cs
> Add support for Search URL

- CloudinaryDotNet.IntegrationTests/CloudinaryDotNet.IntegrationTests.csproj
- CloudinaryDotNet.IntegrationTests/IntegrationTestBase.cs
- CloudinaryDotNet.IntegrationTests/Provisioning/ProvisioningIntegrationTestBase.cs
- CloudinaryDotNet.Tests/CloudinaryDotNet.Tests.csproj
- CloudinaryDotNet.Tests/MockedCloudinary.cs
- appveyor.yml
> Fix test warnings

- CloudinaryDotNet.Tests/SearchApi/SearchFoldersTest.cs
- CloudinaryDotNet.Tests/SearchApi/SearchTest.cs
- CloudinaryDotNet/Actions/Search/SearchFolder.cs
- CloudinaryDotNet/Actions/Search/SearchFoldersResult.cs
- CloudinaryDotNet/Actions/Search/SearchResource.cs
- CloudinaryDotNet/Actions/Search/SearchResult.cs
- CloudinaryDotNet/Actions/Search/SearchResultBase.cs
- CloudinaryDotNet/Cloudinary.AdminApi.cs
- CloudinaryDotNet/Search/Search.cs
- CloudinaryDotNet/Search/SearchBaseFluent.cs
- CloudinaryDotNet/Search/SearchFluent.cs
- CloudinaryDotNet/Search/SearchFolders.cs
- CloudinaryDotNet/Search/SearchFoldersFluent.cs
> Add support for `SearchFolders` API

- CloudinaryDotNet.Tests/UploadPresetsTest.cs
- CloudinaryDotNet/Actions/AssetsUpload/RawUploadParams.cs
- CloudinaryDotNet/Actions/AssetsUpload/UploadResult.cs
- CloudinaryDotNet/Actions/PresetsUpload/GetUploadPresetResult.cs
- CloudinaryDotNet/Actions/PresetsUpload/UploadPresetParams.cs
- CloudinaryDotNet/CloudinaryDotNet.csproj
> Add support for `OnSuccess` upload parameter

- CloudinaryDotNet.IntegrationTests/UploadApi/UploadMethodsTest.cs
- CloudinaryDotNet/Actions/AssetsUpload/VideoUploadResult.cs
Add support for PlaybackUrl in VideoUploadResult #337
> Add support for PlaybackUrl in VideoUploadResult

- CloudinaryDotNet.Tests/Asset/UrlBuilderTest.cs
- CloudinaryDotNet/Transforms/FetchLayer.cs
> Add support for fetch video layer

- CloudinaryDotNet.Tests/AdminApi/VisualSearchTest.cs
- CloudinaryDotNet.Tests/Asset/UrlBuilderTest.cs
- CloudinaryDotNet/Actions/AssetsManagement/VisualSearchParams.cs
- CloudinaryDotNet/Actions/AssetsUpload/BasicRawUploadParams.cs
- CloudinaryDotNet/Actions/BaseParams.cs
- CloudinaryDotNet/ApiShared.Internal.cs
- CloudinaryDotNet/ApiShared.cs
- CloudinaryDotNet/Cloudinary.AdminApi.cs
- CloudinaryDotNet/Cloudinary.UploadApi.cs
- CloudinaryDotNet/Provisioning/AccountProvisioning.cs
- CloudinaryDotNet/Provisioning/ProvisioningApi.cs
- CloudinaryDotNet/Search/SearchFluent.cs
- CloudinaryDotNet/Search/SearchFoldersFluent.cs
> Add support for `ImageFile` in `VisualSearch`

- CloudinaryDotNet/Cloudinary.UploadApi.cs
- CloudinaryDotNet/Cloudinary.cs
- CloudinaryDotNet/CloudinaryDotNet.csproj
- CloudinaryDotNet/ICloudinary.cs
- CloudinaryDotNet/ICloudinaryAdminApi.cs
- CloudinaryDotNet/ICloudinarySearchApi.cs
- CloudinaryDotNet/ICloudinaryUploadApi.cs
- CloudinaryDotNet/Provisioning/AccountProvisioning.cs
- CloudinaryDotNet/Provisioning/IAccountProvisioning.cs
> Add `ICloudinary` interface for `Cloudinary` class

- CloudinaryDotNet.IntegrationTests/SearchApi/SearchApiTest.cs
> Fix SearchApi tests on some environments

- CloudinaryDotNet.IntegrationTests/Provisioning/AccountApi/AccountProvisioningAsyncTest.cs
- CloudinaryDotNet.IntegrationTests/Provisioning/AccountApi/AccountProvisioningTest.cs
- CloudinaryDotNet/Constants.cs
- CloudinaryDotNet/Provisioning/AccountProvisioning.cs
- CloudinaryDotNet/Provisioning/Actions/AccessKeyResult.cs
- CloudinaryDotNet/Provisioning/Actions/GenerateAccessKeyParams.cs
- CloudinaryDotNet/Provisioning/Actions/ListAccessKeysParams.cs
- CloudinaryDotNet/Provisioning/Actions/ListAccessKeysResult.cs
- CloudinaryDotNet/Provisioning/Actions/UpdateAccessKeyParams.cs
- CloudinaryDotNet/Provisioning/IAccountProvisioning.cs
> Add support for access keys management in Account Provisioning API

- CloudinaryDotNet.Tests/Provisioning/AccountProvisioningTest.cs
- CloudinaryDotNet/Provisioning/AccountProvisioning.cs
- CloudinaryDotNet/Provisioning/ProvisioningApi.cs
> Add `AccountProvisioning` constructors

- CloudinaryDotNet.IntegrationTests/AdminApi/BrowseResourcesTest.cs
- CloudinaryDotNet.IntegrationTests/SearchApi/SearchApiTest.cs
- CloudinaryDotNet/Actions/AssetsManagement/ListResourcesParams.cs
- CloudinaryDotNet/Search/SearchBaseFluent.cs
> Add support for `Fields` parameter in Search and Admin APIs

- CloudinaryDotNet.Tests/Asset/UrlBuilderTest.cs
- CloudinaryDotNet/Transforms/FetchLayer.cs
> Fix special characters encoding in `FetchLayer`

- CloudinaryDotNet.Tests/Tag/VideoTagTest.cs
- CloudinaryDotNet/Url.cs
> Add support for `UseFetchFormat` parameter to `BuildVideoTag`

- CloudinaryDotNet.Tests/UploadApi/UploadTest.cs
- CloudinaryDotNet/Actions/AssetsUpload/BasicRawUploadParams.cs
- CloudinaryDotNet/ApiShared.Internal.cs
> Add support for `Signature` and `Timestamp` in `UploadParams`

- CloudinaryDotNet.IntegrationTests/UploadApi/UploadMethodsTest.cs
- CloudinaryDotNet/ApiShared.Internal.cs
- CloudinaryDotNet/Cloudinary.UploadApi.cs
- CloudinaryDotNet/FileDescription.cs
> Add support for uploading non-seekable streams

- CloudinaryDotNet.Tests/AdminApi/RelatedAssetsTest.cs
- CloudinaryDotNet.Tests/Asset/UrlBuilderTest.cs
- CloudinaryDotNet/Cloudinary.AdminApi.cs
- CloudinaryDotNet/Cloudinary.UploadApi.cs
- CloudinaryDotNet/UrlBuilder.cs
- CloudinaryDotNet/Utils.cs
> Fix URL encoding in `DownloadPrivate`

- CloudinaryDotNet.IntegrationTests/IntegrationTestBase.cs
- CloudinaryDotNet.IntegrationTests/UploadApi/UploadMethodsTest.cs
- CloudinaryDotNet/Core/LimitedStream.cs
> Fix `UploadLarge` breaking large files on upload

- CloudinaryDotNet.Tests/Asset/UrlBuilderTest.cs
- CloudinaryDotNet/Actions/AssetsUpload/BasicRawUploadParams.cs
- CloudinaryDotNet/ApiShared.Internal.cs
- CloudinaryDotNet/ApiShared.cs
- CloudinaryDotNet/Cloudinary.UploadApi.cs
- CloudinaryDotNet/FileDescription.cs
* Improve stability
* Cleanup code
> Fix `X-Unique-Upload-Id` header duplicate value

- CloudinaryDotNet.Tests/AdminApi/AnalysisTest.cs
- CloudinaryDotNet.Tests/MockedCloudinary.cs
- CloudinaryDotNet/Actions/Analysis/AnalysisPayload.cs
- CloudinaryDotNet/Actions/Analysis/AnalyzeParams.cs
- CloudinaryDotNet/Actions/Analysis/AnalyzeResult.cs
- CloudinaryDotNet/Actions/Analysis/AnalyzeUriRequestParameters.cs
- CloudinaryDotNet/Actions/Analysis/CustomParameters.cs
- CloudinaryDotNet/Actions/BaseParams.cs
- CloudinaryDotNet/ApiShared.cs
- CloudinaryDotNet/Cloudinary.AdminApi.Analysis.cs
- CloudinaryDotNet/Constants.cs
> Add support for `Analyze` API

- CloudinaryDotNet.IntegrationTests/Provisioning/AccountApi/AccountProvisioningAsyncTest.cs
- CloudinaryDotNet.IntegrationTests/Provisioning/AccountApi/AccountProvisioningTest.cs
- CloudinaryDotNet.IntegrationTests/Provisioning/ProvisioningIntegrationTestBase.cs
- CloudinaryDotNet.Tests/AdminApi/RelatedAssetsTest.cs
- CloudinaryDotNet/ApiShared.Internal.cs
- CloudinaryDotNet/Provisioning/AccountProvisioning.cs
- CloudinaryDotNet/Provisioning/Actions/DelAccessKeyParams.cs
- CloudinaryDotNet/Provisioning/Actions/DelAccessKeyResult.cs
- CloudinaryDotNet/Provisioning/IAccountProvisioning.cs
- CloudinaryDotNet/Provisioning/ProvisioningApi.cs
> Add support for `DeleteAccessKey` in Provisioning API

- CloudinaryDotNet.IntegrationTests/AdminApi/ConfigTest.cs
- CloudinaryDotNet/Actions/AssetsManagement/ConfigParams.cs
- CloudinaryDotNet/Actions/AssetsManagement/ConfigResult.cs
- CloudinaryDotNet/Actions/AssetsManagement/NestedTypes/AccountSettings.cs
- CloudinaryDotNet/Cloudinary.AdminApi.cs
- CloudinaryDotNet/ICloudinaryAdminApi.cs
> Add support for `GetConfig` Admin API

- CloudinaryDotNet.IntegrationTests/AdminApi/ManageFoldersTest.cs
- CloudinaryDotNet.IntegrationTests/Provisioning/ProvisioningIntegrationTestBase.cs
- CloudinaryDotNet/Actions/Folders/RenameFolderParams.cs
- CloudinaryDotNet/Actions/Folders/RenameFolderResult.cs
- CloudinaryDotNet/Cloudinary.AdminApi.cs
- CloudinaryDotNet/ICloudinaryAdminApi.cs
> Add support for `RenameFolder` Admin API

- CloudinaryDotNet/Utils.cs
> Fix epoch time conversion discrepancy

- CloudinaryDotNet.IntegrationTests/IntegrationTestBase.cs
- CloudinaryDotNet.IntegrationTests/UploadApi/UploadMethodsTest.cs
- CloudinaryDotNet/Cloudinary.UploadApi.cs
- CloudinaryDotNet/Core/LimitedStream.cs
- CloudinaryDotNet/FileDescription.cs
> Fix race condition in `UploadLarge` with parallel upload

- CloudinaryDotNet.Tests/Asset/SignatureTest.cs
- CloudinaryDotNet/Url.cs
> Fix `format` handling in signed URLs

- CloudinaryDotNet.Tests/AdminApi/GetResourceTest.cs
- CloudinaryDotNet/Actions/JsonConverter/ModerationResponseConverter.cs
- CloudinaryDotNet/Actions/ModerationLabel.cs
> Fix `duplicates` moderation response

- CloudinaryDotNet.Tests/Asset/SignatureTest.cs
- CloudinaryDotNet/ApiShared.cs
- CloudinaryDotNet/ISignProvider.cs
> Fix API parameters signature
